### ISSUE TITLE
orgEntry

### ISSUE THREAD

**Issue by arthursoares** [envisioning/techdb#27]
This is the editing screen for organizations. You should be able to perform all actions regarding them inside this screen.

## Features

- [x] List and edit all data ( #7 for scheme)
- [x] Add projects
- [x] Add technologies
- [x] Add Attachments.

## Elements

- orgAboutBox
- projectList --> Milestone 2 vira projectGridCard
- technologyList --> Milestone 2 vira technologyGridCard
- attachmentList --> Milestone 2 vira attachmentGridCard

**Comment by arthursoares** [comment]
A screen to show everything about a specific organization

## Specification
Composed by two main components:
### Organization card on the left panel
orgCard #35

### Tabholder on the right panel with these tabs:
- Projects
- Techs
- Attachments

Each tab will have a simpleList #36 with the associated entities and a link for them

![screen organization entry](https://cloud.githubusercontent.com/assets/4376835/12218523/e6b105ca-b708-11e5-8062-c338f2390be5.png)


----

by @rafaelcorreiapoli

**Comment by arthursoares** [comment]
@rafaelcorreiapoli I think it is best to have separate panels/ibox instead of using Tabs for showing projects/technologies/attachments.

:)

**Comment by rafaelcorreiapoli** [comment]
Ok! just like userEntry #25 , right ?

**Comment by arthursoares** [comment]
Yes!
On Sun, Jan 10, 2016 at 00:29 Rafael Ribeiro <notifications@github.com>
wrote:

> Ok! just like userEntry #25
> <https://github.com/envisioning/techdb/issues/25> , right ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/envisioning/techdb/issues/27#issuecomment-170301405>.
>
-- 
+55 11 96960.6666
http://arthur.wtf

**Comment by rafaelcorreiapoli** [comment]
Hey guys, I would like to discuss some details on this screen
![org entry](https://cloud.githubusercontent.com/assets/12840136/12629722/3fbae2be-c530-11e5-9e01-842aa5ef4527.png)


**1. Manage people**
Clicking on the plus sign, I will open up a modal that shows two elements:
A simple table of key people, since it's not going to be a big list (I think), there will be no search field. The rows will display the Picture, Name, Role and Actions. on the column actions we will have two buttons: Delete and Google Search, to quickly open google with the name on the search field.
A simple form to add new people with three inputs:
Name, Role, Link for a pic of this person


**2. Add projects**
It will open up a modal with a search field that will make an elasticsearch (by title and description, just like #32) but it will filter only Projects. I don't know how to display the results and I would like to know your opnion. 

**3. Add Technologies **
Same as **2.**

**4. Add attachments **
We must present the user a form to create a new attachment, I think that this can be done via a Modal. But what if the user wants to attach an attachment that already exists on our database? Any ideas of UI/UX ?

**Comment by michellzappa** [comment]
1. People within an Organization: low-low-low priority. Not important at
all.
2. OK.
3. Yes, important.
4. Attachments will require a Modal, in deed. UX needs to be sketched.

**Comment by lnmunhoz** [comment]
:+1:

**Comment by lnmunhoz** [comment]
@arthursoares If you agree with the following items. Can close this issue!

1. I think if key people exists, we should give more attention and create a basic CRUD for them with more informations about it. Because this way is not relevant at all. What you guys think to rethink at Milestone 2?
2. Done
3. Done
4. Done at #63. I don't think that a modal is the best approach for this. We did a screen that's already deployed.

**Comment by arthursoares** [comment]
1) Yes, if people exist within an organization there should be a CRUD operation.

**Comment by rafaelcorreiapoli** [comment]
I think that @lnmunhoz meant that we should create a collection for People instead of just creating subdocuments, am I right?

**Comment by lnmunhoz** [comment]
Yes @rafaelcorreiapoli
