### ISSUE TITLE
Not displaying users image on dashboard

### ISSUE THREAD

**Issue by lnmunhoz** [envisioning/techdb#74]
After the S3 configuration 42d0b5c544a3daf6510914091d605fe4dde2f831, the images are not displaying on dashboard anymore. (I don't remember if isn't before).

![screenshot from 2016-02-19 02 14 42](https://cloud.githubusercontent.com/assets/4376835/13166466/66cb51be-d6af-11e5-8c1d-a04457364969.png)

**Comment by rafaelcorreiapoli** [comment]
I deleted all files from our S3 for testing purposes, those images does not exist anymore, it is not related to techdb itself

**Comment by rafaelcorreiapoli** [comment]
Anyway, we must implement a fallback image on the component safeImg to handle 404

**Comment by rafaelcorreiapoli** [comment]
Ah, ok, I think there is something wrong, im reopening the issue

**Comment by rafaelcorreiapoli** [comment]
Ok, I found out what was happening.
You changed the bucket and folder structure of our uploaded images on S3 and this caused a mapping problem with cloudinary,
http://cloudinary.com/documentation/fetch_remote_images
please read the topic "Auto upload"
We must configure mappings on cloudinary so it knows where to look on the web when you ask for some image
The problem was solved with this:
![envs](https://cloud.githubusercontent.com/assets/12840136/13195927/36011e22-d7a6-11e5-9859-ff21256a3cda.png)
